"""
CAR CONFIG

This file is read by your car application's manage.py script to change the car
performance.

EXMAPLE
-----------
import dk
cfg = dk.load_config(config_path='~/mycar/config.py')
print(cfg.CAMERA_RESOLUTION)

"""


import os

# PATHS
CAR_PATH = PACKAGE_PATH = os.path.dirname(os.path.realpath(__file__))
DATA_PATH = os.path.join(CAR_PATH, 'data')
MODELS_PATH = os.path.join(CAR_PATH, 'models')

# VEHICLE
DRIVE_LOOP_HZ = 20
MAX_LOOPS = 100000

# CAMERA
CAMERA_RESOLUTION = (120, 160) #(height, width)
CAMERA_FRAMERATE = DRIVE_LOOP_HZ

# SUPERSONIC RANGING SENSOR
#RANGE_TRIG_GPIO = 5
#RANGE_ECHO_GPIO = 6
#RANGE_GPIOS = [
#    RANGE_TRIG_GPIO,
#    RANGE_ECHO_GPIO
#]

# SPI
#SPI_VERF_VOLTS = 3.3
#SPI_CHANNEL = 0
#SPI_BAUD = 50000
#SPI_FLAGS = 0
#
#SPI_SETTINGS = [
#    SPI_VERF_VOLTS,
#    SPI_CHANNEL,
#    SPI_BAUD,
#    SPI_FLAGS
#]

# FORCE SENSOR
#ADC_CH_FORCE = 0
# BENDING SENSOR
#ADC_CH_BEND = 1


## TA7291P (Fake-PWM)

# LEFT MOTOR
LEFT_MOTOR_PWM_GPIO = 16
LEFT_MOTOR_IN1_GPIO = 20
LEFT_MOTOR_IN2_GPIO = 21
LEFT_MOTOR_GPIOS = [
    LEFT_MOTOR_IN1_GPIO,
    LEFT_MOTOR_IN2_GPIO,
    LEFT_MOTOR_PWM_GPIO]

# RIGHT MOTOR
RIGHT_MOTOR_PWM_GPIO = 13
RIGHT_MOTOR_IN1_GPIO = 19
RIGHT_MOTOR_IN2_GPIO = 26
RIGHT_MOTOR_GPIOS = [
    RIGHT_MOTOR_IN1_GPIO,
    RIGHT_MOTOR_IN2_GPIO,
    RIGHT_MOTOR_PWM_GPIO]

# LIFT MOTOR
#LIFT_MOTOR_PWM_GPIO = 17
#LIFT_MOTOR_IN1_GPIO = 27
#LIFT_MOTOR_IN2_GPIO = 22
#LIFT_MOTOR_GPIOS = [
#    LIFT_MOTOR_IN1_GPIO,
#    LIFT_MOTOR_IN2_GPIO,
#    LIFT_MOTOR_PWM_GPIO]

# POWER UNIT GPIOS
PU_GPIOS = [
    LEFT_MOTOR_GPIOS,
    RIGHT_MOTOR_GPIOS,
#    LIFT_MOTOR_GPIOS
]

## DRV8830 (I2C)
#LEFT_MOTOR_I2CBUS = 1
#LEFT_MOTOR_SLAVE_ADDRESS = 0x65
#LEFT_MOTOR_MAX_VOLTAGE = 1.50
#LEFT_MOTOR_SETTINGS =[
#    LEFT_MOTOR_I2CBUS,
#    LEFT_MOTOR_SLAVE_ADDRESS,
#    LEFT_MOTOR_MAX_VOLTAGE
#]

#RIGHT_MOTOR_I2CBUS = 1
#RIGHT_MOTOR_SLAVE_ADDRESS = 0x64
#RIGHT_MOTOR_MAX_VOLTAGE = 1.50
#RIGHT_MOTOR_SETTINGS =[
#    RIGHT_MOTOR_I2CBUS,
#    RIGHT_MOTOR_SLAVE_ADDRESS,
#    RIGHT_MOTOR_MAX_VOLTAGE
#]

#LIFT_MOTOR_I2CBUS = 1
#LIFT_MOTOR_SLAVE_ADDRESS = 0x63
#LIFT_MOTOR_MAX_VOLTAGE = 1.50
#LIFT_MOTOR_SETTINGS =[
#    LIFT_MOTOR_I2CBUS,
#    LIFT_MOTOR_SLAVE_ADDRESS,
#    LIFT_MOTOR_MAX_VOLTAGE
#]

#PU_SETTINGS = [
#    LEFT_MOTOR_SETTINGS,
#    RIGHT_MOTOR_SETTINGS,
#    LIFT_MOTOR_SETTINGS
#]

## Marvelmind Mobile Beacon
HEDGEHOG_ADDRESS = 19
HEDGEHOG_SERIAL_TTY = '/dev/ttyACM0'
HEDGEHOG_SERIAL_BAUD = 9600


# AWS IoT Hub
AWS_YAML_PATH = 'conf/aws/smith.yml'
AWS_YAML_TARGET = 'smith'


# TRAINING
BATCH_SIZE = 128
TRAIN_TEST_SPLIT = 0.8


# JOYSTICK

# TUB
TUB_PATH = os.path.join(CAR_PATH, 'tub') # if using a single tub

# ROPE.DONKEYCAR.COM
ROPE_TOKEN="GET A TOKEN AT ROPE.DONKEYCAR.COM"
